config/routes.rb
Travelobd::Application.routes.draw do

  resources :ownership_requests do
    member do
      get :accept
    end
  end

  resources :club_joining_requests do
    member do
      post :approve
      post :deny
    end
  end

  resources :tour_clubs do
    resources :comments
    collection do
      get :search
    end

    member do
      get :print
      post :rate
      post :join_leave
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'users#failure'

  resources :authentications

  resources :tour_operators do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :transports do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :rooms

  resources :password_reset

  resources :profiles

  resources :hotels do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_spots
    end
    member do
      get :print
      post :rate
    end
  end

#

  resources :packages do
    resources :comments

    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :location_autocomplete
      get :load_cities
    end
    member do
      get :print
      post :rate
    end
  end

  resources :messages

  resources :spots do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_nearby_spots
    end
    member do
      get :print
      post :rate
    end
  end

  resources :elements

  resources :articles do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end
    member do
      get :print
      post :rate
    end
  end

  resources :profiles do
    member do
      get :spots
      get :articles
    end
  end

  resource :user_session
  resources :users do
    collection do
      post :save_item
      post :remove_saved_item
      get :load_uploaded_images
      post :upload_images
    end
    resource :profile
  end

  get "welcome/index"
  get "welcome/load_districts"
  get "users/dashboard"


  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  #match 'checkout' => 'carts#show'
  root :to => "welcome#index"

  #ajax on home page
  get 'welcome/articles'
  get 'welcome/other_classifieds'
  get 'welcome/featured_ads'
  get 'welcome/spots'


  match 'advance_search' =>'ads#advance_search'


  #dashboard
  match 'dashboard' => 'users#dashboard'
  match 'inbox' => 'users#inbox'
  match 'outbox' => 'users#outbox'
  match 'my_saved_listings' => 'users#saved_listings'
  match 'my_spots' => 'users#spots'
  match 'my_packages' => 'users#packages'
  match 'my_hotels' => 'users#hotels'
  match 'my_rooms' => 'users#rooms'
  match 'my_transports' => 'users#transports'
  match 'my_clubs' => 'users#clubs'
  match 'my_articles' => 'users#articles'
  match 'my_tour_operators' => "users#tour_operators"
  match 'send_to_friends' => 'users#send_to_friends'
  match 'club_leaving_requests' => 'club_joining_requests#leaving_requests'


  #newly added
  match 'tell_friends' => 'users#tell_friends'

  post 'assets/update_label', :as => :update_asset_label

end

app/views/shared_partials/_branch_location.html.erb
<div class="event branch_location">

  <%= form.fields_for :branch_locations, branch_location, :child_index => (branch_location.new_record? ? "index_to_replace_with_js" : nil) do |branch_location_form| %>
      <div class="package_event_time">
        <%= t('general.label.district') %>
      </div>
      <div class="package_contact_address">
         <%= t('general.label.name')%>
      </div>

      <div class="package_event_time clear">
        <%= branch_location_form.select :district_id, District.all.collect { |d| [d.name, d.id] }, :include_blank => '--Select--', :class => 'event' %>
      </div>
      <div class="package_contact_address">
        <%= branch_location_form.text_field :location, :class => 'event' %>
      </div>

      <div class="package_event_time clear">
        <%= t('general.label.phone')%>
      </div>
      <div class="package_contact_address fl">
        <%= t('general.label.address')%>
      </div>

      <div class="package_event_time clear">
        <%= branch_location_form.text_field :phone, :class => 'event' %>
      </div>

      <div class="package_contact_address">
        <%= branch_location_form.text_area :address, :class => 'event' %>
      </div>

      <div class="deleteLink">
        <% if branch_location.new_record? %>
            <span class="removeBranchLocationField"> <%= t('general.label.remove')%></span>
        <% else %>
            <%= branch_location_form.check_box :_destroy %>
            <span class="deleteLink deleteLinkCheckbox">
              <%= t('helpers.delete') %>
            </span>
        <% end %>
      </div>
  <% end %>

</div>

app/views/shared_partials/_condition.html.erb
<div class="event condition">

  <%= form.fields_for :conditions, condition, :child_index => (condition.new_record? ? "index_to_replace_with_js" : nil) do |condition_form| %>
      <div class="package_event_time">
        &nbsp;
      </div>
      <div class="package_contact_address">
        <%= t('general.label.condition')%>
      </div>

      <div class="package_event_time clear">
        &nbsp;
      </div>
      <div class="package_contact_address">
        <%= condition_form.text_area :detail, :class => 'event' %>
      </div>


      <div class="deleteLink">
        <% if condition.new_record? %>
            <span class="removeConditionField"> <%= t('general.label.remove')%></span>
        <% else %>
            <%= condition_form.check_box :_destroy %>
            <span class="deleteLink deleteLinkCheckbox">
              <%= t('helpers.delete') %>
            </span>
        <% end %>
      </div>
  <% end %>

</div>

app/views/shared_partials/_contact.html.erb
<div class="event contact">

  <%= form.fields_for :contacts, contact, :child_index => (contact.new_record? ? "index_to_replace_with_js" : nil) do |contact_form| %>
      <div class="package_event_time">
        <%= t('general.label.name')%>
      </div>
      <div class="package_contact_address">
        <%= t('general.label.email')%>
      </div>

      <div class="package_event_time clear">
        <%= contact_form.text_field :name, :class => 'event' %>
      </div>
      <div class="package_contact_address">
        <%= contact_form.text_field :email, :class => 'event' %>
      </div>

      <div class="package_event_time clear">
        <%= t('general.label.phone')%>
      </div>
      <div class="package_contact_address fl">
        <%= t('general.label.address')%>
      </div>


      <div class="package_event_time clear">
        <%= contact_form.text_field :phone, :class => 'event' %>
      </div>
      <div class="package_contact_address">
        <%= contact_form.text_area :address, :class => 'event' %>
      </div>

      <div class="deleteLink">
        <% if contact.new_record? %>
            <span class="removeContactField cross"> X<%#= t('general.label.remove')%></span>
        <% else %>
            <%= contact_form.check_box :_destroy %>
            <span class="deleteLink deleteLinkCheckbox">
              <%= t('helpers.delete') %>
            </span>
        <% end %>
      </div>
  <% end %>

</div>

app/views/shared_partials/_detail_page_comment.html.erb
<div class="good_item_head">
  <%= t('activerecord.models.comment') %>
</div>
<div class="itemDetail" id="item_comments" style="padding-left:0">
  <%= render item.approved_comments %>
</div>
<div class="itemDetail" style="padding-left:0">
  <div class="eventTitle">

     <%= t('general.label.your') %>
     <%= t('activerecord.models.comment') %>
    <% if rating %>
        <div style="float:right">
          <%= t('general.label.rating') %>
           <%= ratings_for item %>
        </div>
    <% end %>
  </div>

  <div class="commentForm">

    <%= render :partial => 'comments/form', :locals => {:comment => item.comments.new, :commentable => item} %>
  </div>
</div>

app/views/shared_partials/_detail_page_photo_gallery.html.erb
<% if items.size > 0 %>
    <div id="" class="good_slide_bor">
      <div id="detail_page_photo_gallery" class="galleryview">

        <% items.each do |asset| %>
            <div class="panel ">
              <%= image_tag(asset.photo.url(:medium), :class=> 'panel_image', :photo_id =>asset.id, :width => 680, :height => 280) %>
            </div>
            <ul class="filmstrip">
              <% items.each do |asset| %>
                  <li class="slide_img">
                    <%= image_tag(asset.photo.url(:thumb_s), :class=> 'panel_image', :photo_id =>asset.id, :width => 60, :height => 51) %>
                  </li>
              <% end %>
            </ul>
        <% end %>

      </div>
    </div>
<% end %>

app/views/shared_partials/_edit_asset_label.html.erb
<div id="edit_asset_label_lb" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb standard_close_lb edit_image_label_lb', :id => '', :title => 'close' %>
  <%= render :partial => 'shared_partials/edit_photo_label_form' %>
</div>

app/views/shared_partials/_edit_photo_label_form.html.erb
<h2 style=" margin-bottom: 20px; margin-top: 5px;">Edit label</h2>

<%= form_for Asset.new, :url=> update_asset_label_path, :remote=> true, :html=> {:id=> 'edit_asset_label_form'} do |f| %>
    <div id="edit_label_status" class="white_Desc">

    </div>
    <div class="white_Desc">
      <label>Image Description:</label>
      <%= text_area_tag :asset_label, :class => 'bangla_input' %>
    </div>

    <div class="submit_btn" style="padding-left:100px;">
      <div id="submit_to_update">
        <input class="search_button" name="" value="Update" type="submit">
        <span class="search_button_right"> </span>
      </div>
      <%= image_tag 'loadingAnimation.gif', :id => 'edit_asset_label', :style=> 'display:none' %>
      <%= hidden_field_tag :asset_id %>
    </div>
<% end %>

app/views/shared_partials/_existing_photo.html.erb
<div class="edit_box_img existing_image">
  <div class="e_bor">
    <%= image_tag existing_photo.photo.url(:thumb), :id => "asset_#{existing_photo.id}", :title => existing_photo.label %>
  </div>
  <%= link_to t('helpers.delete'), 'javascript:void(0)', :asset_id => existing_photo.id, :class => 'del_photo' %>
  <%= link_to t('general.label.edit_label'), 'javascript:void(0)', :id => "asset_link_#{existing_photo.id}", :asset_id => existing_photo.id, :class => 'edit_asset_label', :title => existing_photo.label %>
  <%= check_box_tag "main_check_#{existing_photo.id}", existing_photo.id, existing_photo.main?, :asset_id =>existing_photo.id, :class=> 'mainCh' %>
  <%= t('general.label.main_image') %>
</div>

app/views/shared_partials/_ownership_request.html.erb
<div id="ownership_request_lb" class="" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb close_ownership_request_lb', :id => 'close_ownership_request_lb', :title => 'close' %>
  <% form_for OwnershipRequest.new, :url => ownership_requests_path, :remote => true, :html=> {:id => 'ownership_requests_form'} do |f| %>
      <h2 class="thickbox_header">
        <%= t('general.label.own_this_label') %>
      </h2>

      <div id="ownership_request_summary"  class="tb_form_summary">

      </div>
      <label>
        <%= t('general.label.name') %>
      </label>

      <p class="message">
        <%= f.text_field :name %>
      </p>
      <label>
        <%= t('general.label.designation') %>
      </label>

      <p class="message">
        <%= f.text_field :designation %>
      </p>
      <label>
        <%= t('general.label.company') %>
      </label>

      <p class="message">
        <%= f.text_field :company %>
      </p>

      <label>
        <%= t('general.label.email') %>
      </label>

      <p class="message">
        <%= f.text_field :email %>
      </p>

      <label>
        <%= t('general.label.phone') %>
      </label>

      <p class="message">
        <%= f.text_field :phone %>
      </p>

      <label>
        <%= t('activerecord.models.message') %>
      </label>

      <p class="message">
        <%= f.text_area :message %>
      </p>



      <p style="text-align: center">
        <%= f.hidden_field :resource_id, :value => item_id %>
        <%= f.hidden_field :resource_type, :value => item.classify %>
        <%= submit_tag t("helpers.submit.send"), :id =>'submit_to_own' %>
        <%= image_tag 'loadingAnimation.gif', :id => 'submit_to_own_loading', :style=> 'display:none' %>
      </p>
  <% end %>


</div>

app/views/shared_partials/_photo.html.erb
<div class="photo">
  <%= form.fields_for :assets, photo, :child_index => (photo.new_record? ? "index_to_replace_with_js" : nil) do |photo_form| %>
      <%= photo_form.file_field :photo, :class => 'photo file'%>
      <%= photo_form.text_area :photo_label , :class => 'bangla_input'%>
      <div class="removeLink cross ">
        <span class="removeImageField">X <%#= t('general.label.remove') %></span>
      </div>
  <% end %>

</div>

app/views/shared_partials/_policy.html.erb
<div class="event policy">

  <%= form.fields_for :policies, policy, :child_index => (policy.new_record? ? "index_to_replace_with_js" : nil) do |policy_form| %>
      <div class="package_event_time">
        <%= t('general.label.title')%>
      </div>
      <div class="package_contact_address">
         <%= t('general.label.details')%>
      </div>

      <div class="package_event_time clear">
        <%= policy_form.text_field :title, :class => 'event' %>
      </div>
      <div class="package_contact_address">
        <%= policy_form.text_area :detail, :class => 'event' %>
      </div>


      <div class="deleteLink ">
        <% if policy.new_record? %>
            <span class="removePolicyField cross">X <%#= t('general.label.remove')%></span>
        <% else %>
            <%= policy_form.check_box :_destroy %>
            <span class="deleteLink deleteLinkCheckbox">
              <%= t('helpers.delete') %>
            </span>
        <% end %>
      </div>
  <% end %>

</div>

app/views/shared_partials/_saved_item.html.erb
<% if @already_saved %>
    <%= link_to ' [ ' + t('general.label.remove') + ' ] ', 'javascript:void(0)', :class => 'remove_from_save_listing', :sl_id=> @already_saved.id, :savable_id => savable.id, :savable_type => savable.class.name %>  <%= link_to t('general.label.already_saved'), my_saved_listings_path %>  &nbsp;
<% else %>
    <%= link_to t('helpers.submit.save'), 'javascript:void(0)', :class => 'save_item', :savable_type => savable.class.name, :item_id=> savable.id %>
<% end %>

app/views/shared_partials/_send_to_friends.html.erb
<div id="send_to_friend_lb" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb', :id => 'close_send_to_friend_lb', :title => 'close' %>
  <% form_for :contact, :url => send_to_friends_path, :remote => true, :html=> {:id => 'send_to_friends_form'} do |f| %>
      <h2>
        <%= t('general.label.tell_your_friends') %>
      </h2>

      <div id="stf_summary" style="margin-top: 5px;">

      </div>
      <p>
        <%= t('activerecord.models.message') %>
      </p>

      <p class="message">
        <%= text_area_tag :message %>
      </p>

      <p>
        <%= t('general.label.email') %>
      </p>

      <p class="message">
        <%= text_area_tag :email %>
      </p>

      <p style="text-align: center">
        <%= hidden_field_tag 'item_id', item_id %>
        <%= hidden_field_tag 'item_type', item %>
        <%= submit_tag t("helpers.submit.send"), :id =>'submit_to_friend' %>
        <%= image_tag 'loadingAnimation.gif', :id => 'sending_to_friend', :style=> 'display:none' %>
      </p>
  <% end %>


</div>

app/views/shared_partials/_tiny_redcloth_image.html.erb
<div id="tiny_redcloth_image" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb', :id => 'close_tiny_redcloth_image', :title => 'close' %>
  <h3>Uploaded Images
    <small> [click on images to select]</small>
  </h3>

  <div id="tiny_redcloth_image_container">
    <%= image_tag 'loadingAnimation.gif' %>
  </div>

  <div class="field">
    <label>
      Insert URL
    </label>
    <input type="text" id="inserted_url" style="width:488px"/>
    <button id="inserted_url_button">GO</button>
    <br/>
    Or Upload Images <br/>

  </div>
  <div class="tiny_redcloth_image_form_container">
    <%= form_for(current_user, :url => upload_images_users_path, :html=> {:multipart => true, :id=> 'user_image_upload_form'}) do |f| %>

        <div id="user_uploaded_photos">
          <%= render :partial => 'users/upload_image', :locals => {:form => f, :photo => current_user.uploaded_images.new} %>
        </div>
        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreImageToUpload' %>

        <div class="actions fl">
          <button value="Upload" id='submit_user_upload'>Upload</button>
        </div>
        <% @user_form_builder = f %>
    <% end %>

    <div id="new_user_image_html" style="display:none;">
      <%= render :partial => 'users/upload_image', :locals => {:form => @user_form_builder, :photo => current_user.uploaded_images.new} %>
    </div>
  </div>
</div>