config/routes.rb
Travelobd::Application.routes.draw do

  resources :ownership_requests do
    member do
      get :accept
    end
  end

  resources :club_joining_requests do
    member do
      post :approve
      post :deny
    end
  end

  resources :tour_clubs do
    resources :comments
    collection do
      get :search
    end

    member do
      get :print
      post :rate
      post :join_leave
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'users#failure'

  resources :authentications

  resources :tour_operators do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :transports do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :rooms

  resources :password_reset

  resources :profiles

  resources :hotels do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_spots
    end
    member do
      get :print
      post :rate
    end
  end

#

  resources :packages do
    resources :comments

    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :location_autocomplete
      get :load_cities
    end
    member do
      get :print
      post :rate
    end
  end

  resources :messages

  resources :spots do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_nearby_spots
    end
    member do
      get :print
      post :rate
    end
  end

  resources :elements

  resources :articles do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end
    member do
      get :print
      post :rate
    end
  end

  resources :profiles do
    member do
      get :spots
      get :articles
    end
  end

  resource :user_session
  resources :users do
    collection do
      post :save_item
      post :remove_saved_item
      get :load_uploaded_images
      post :upload_images
    end
    resource :profile
  end

  get "welcome/index"
  get "welcome/load_districts"
  get "users/dashboard"


  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  #match 'checkout' => 'carts#show'
  root :to => "welcome#index"

  #ajax on home page
  get 'welcome/articles'
  get 'welcome/other_classifieds'
  get 'welcome/featured_ads'
  get 'welcome/spots'


  match 'advance_search' =>'ads#advance_search'


  #dashboard
  match 'dashboard' => 'users#dashboard'
  match 'inbox' => 'users#inbox'
  match 'outbox' => 'users#outbox'
  match 'my_saved_listings' => 'users#saved_listings'
  match 'my_spots' => 'users#spots'
  match 'my_packages' => 'users#packages'
  match 'my_hotels' => 'users#hotels'
  match 'my_rooms' => 'users#rooms'
  match 'my_transports' => 'users#transports'
  match 'my_clubs' => 'users#clubs'
  match 'my_articles' => 'users#articles'
  match 'my_tour_operators' => "users#tour_operators"
  match 'send_to_friends' => 'users#send_to_friends'
  match 'club_leaving_requests' => 'club_joining_requests#leaving_requests'


  #newly added
  match 'tell_friends' => 'users#tell_friends'

  post 'assets/update_label', :as => :update_asset_label

end

app/models/transport.rb
class Transport < ActiveRecord::Base
  translates :name, :description, :address
  default_scope order('transports.created_at DESC')

  has_many :polymorphic_categories, :as => :categorizable, :dependent => :destroy
  has_many :categories, :through => :polymorphic_categories, :dependent => :destroy

  has_many :assets, :as => :assetable, :dependent => :destroy
  has_one :main_image, :class_name => 'Asset', :as => :assetable, :conditions => {:main => true}
  belongs_to :user
  has_many :branch_locations, :as => :branchable
  has_many :contacts, :as => :contactable
  has_many :policies, :as => :policiable
  has_many :comments, :as => :commentable
  has_many :approved_comments, :as => :commentable, :class_name => 'Comment', :conditions => {:approved => true}
  has_many :saved_listings, :as => :savable, :dependent => :destroy
  has_and_belongs_to_many :destinations, :class_name => "District", :join_table => 'transports_destinations'
  has_and_belongs_to_many :spots
  has_many :departure_schedules

  has_friendly_id :name, :use_slug => true
  validates :name, :presence => true
  validates :description, :presence => true

  accepts_nested_attributes_for :assets, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :contacts, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :policies, :reject_if => lambda { |a| a[:detail].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :branch_locations, :reject_if => lambda { |a| a[:location].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :departure_schedules, :reject_if => lambda { |a| a[:time].blank? }, :allow_destroy => true

  ajaxful_rateable :stars => 5, :allow_update => false, :dimensions => [:useful, :price]


  CATEGORIES = {'cat1' => 1, 'cat2' => 2, 'cat3' => 3}

  scope :featured, where(:featured => true).includes(:translations, :assets, :main_image, :slug)

  def main_image_url(style = :medium)
    main_image ? main_image.photo.url(style) : assets.size > 0 ? assets.first.photo.url(style) : ''
  end

  def category
   categories.collect(&:title).join(',')
  end

  def locations
    '&nbsp;'
  end

  def locations_by_districts
    branch_locations.group_by { |b| b.district }
  end

end

app/controllers/admin/transports_controller.rb
class Admin::TransportsController < Admin::ResourcesController
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_filter :require_user, :only=> [:new, :edit, :create, :update, :destroy]
  before_filter lambda { @active_nav = 'transports' }
  before_filter :load_item, :only =>[:show, :edit, :update, :destroy, :print, :rate]
  before_filter :check_ownership, :only => [:edit, :update]
  before_filter :check_if_owner, :only => [:destroy]
  layout :choose_layout
  # GET /ads
  # GET /ads.xml
  def index
    @transports = Transport.paginate(:page=> params[:page], :per_page => 3)
    @paginate_items = @transports
    render :action => 'index_admin', :layout => 'admin' if admin?
  end

  # GET /ads/1
  # GET /ads/1.xml
  def show
    @already_saved = SavedListing.in_my_list(current_user.id, @transport.id, 'Transport') if current_user
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @transport }
    end
  end

  # GET /ads/new
  # GET /ads/new.xml
  def new
    @transport = Transport.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.xml
  def create
    @transport = Transport.new(params[:transport])
    @transport.user_id = current_user.id
    respond_to do |format|
      if @transport.save
        format.html { redirect_to(@transport, :notice => t('general.label.item_created', :item => t('activerecord.models.transport'))) }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @transport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.xml
  def update
    params[:transport][:destination_ids] ||= []
    respond_to do |format|
      if @transport.update_attributes(params[:transport])
        format.html { redirect_to(@transport, :notice => t('general.label.item_update', :item => t('activerecord.models.transport'))) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @transport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.xml
  def destroy
    @transport.destroy

    respond_to do |format|
      format.html { redirect_to(transports_url) }
      format.xml { head :ok }
    end
  end

  def delete_asset
      asset = Asset.find(params[:asset_id])
      asset.destroy
      render :nothing => true
    end

    def set_main_photo
      asset = Asset.find(params[:asset_id])
      Asset.update_all ['main = ?', false], ['assetable_type = ? AND assetable_id = ?', 'Transport', asset.assetable_id]
      asset.update_attribute(:main, true)
      render :nothing => true
    end




  def location_autocomplete
    districts = District.includes(:division).where(['districts.name like ?  OR divisions.name like ?', "%#{params[:term]}%", "%#{params[:term]}%"]).limit(15)
    render :json => districts.collect { |c| {"id" => c.id, "label" => "#{c.name}, #{c.division.name if c.division}", "value" => c.name} }
  end


  def search
    @transport_search = Transport.search(params[:search])
    @transports = @transport_search.paginate(:page=> params[:page], :per_page => 15)
    @search_label = params[:label] || 'Transports : Search Results '
    @paginate_items = @transports
    render :index
  end


  def print
    render :layout => 'print'
  end

  def rate
    @transport.rate(params[:stars], current_user, params[:dimension])
    respond_to do |format|
      format.js { render :partial => '/comments/rate', :locals => {:obj => @transport} }
    end

  end


  private

  def load_item
    @transport = Transport.find(params[:id])
  end

  def check_ownership
     current_user && (current_user.id == @transport.user_id || OwnershipRequest.owned('Transport', current_user.id).collect(&:resource_id).include?(@transport.id))
   end

   def check_if_owner
     ownership_require(@transport)
   end

  def choose_layout
    ['new', 'edit'].include?(action_name) ? 'dashboard' : 'application'
  end
end

app/helpers/transports_helper.rb
module TransportsHelper

  def departure_schedules(transport)
    html = ''
    transport.departure_schedules.each do |schedule|
      html << "<div class='#{cycle('evenRow', 'oddRow')}'>"
      html << "<div class='eventTitle' style='margin-bottom: 0px'>#{schedule.route}</div>"
      html << "<div class=' departure_times'>#{schedule.time.split(',').collect { |item| '<span class="departure_time">'+ item + '</span>' }.join(' ')}</div>"
      html << "</div>"
    end
    html
  end
end

app/views/transports/_form.html.erb
<% title localized_item_header(@transport) %>
<div class="pageHead">
  <%= localized_item_header(@transport) %>
</div>


<%= content_for :js_css_include do %>
    <%= javascript_include_tag 'jquery.validate', 'tiny_redcloth', 'jquery-fieldselection', 'thickbox' %>
    <%= stylesheet_link_tag 'jquery-ui', 'autocomplete', 'thickbox' %>
<% end %>
<div class="item_form">

<%= form_for(@transport, :html => {:multipart => true, :id=> 'transport_form'}) do |f| %>
    <% @builder = f %>
    <%= error_messages_for(@transport) %>

    <div class="form_summary" id="summary"></div>

    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.category') %>
        <span>*</span>
      </div>

     <div class="f_edit_row photo_box">
          <% for category in Category.transport_categories %>
              <div class="spot_in_package district_in_transport">
                <%= check_box_tag "transport[category_ids][]", category.id, @transport.categories.include?(category), :id => dom_id(category) %>

                <label for="<%= dom_id(category) %>"><%= category.title %></label>
              </div>
          <% end %>
        </div>
    </div>


    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.name') %>
        <span>*</span>
      </div>
      <%= f.text_field :name %>
    </div>


    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.description') %>
        <span>*</span>
      </div>
      <%= f.text_area :description, :rows => 20, :cols => 80 %>
    </div>


    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.website') %>

      </div>
      <%= f.text_field :web %>
    </div>


    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.destinations') %>

      </div>

      <div class="f_edit_row photo_box">
        <% for district in District.actives %>
            <div class="spot_in_package district_in_transport">
              <%= check_box_tag "transport[destination_ids][]", district.id, @transport.destinations.include?(district), :id => dom_id(district) %>

              <label for="<%= dom_id(district) %>"><%= district.name %></label>
            </div>
        <% end %>
      </div>


    </div>
    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.spots') %>

      </div>

      <div class="f_edit_row photo_box">
        <% for spot in Spot.actives.includes(:district) %>
            <div class="spot_in_package spot_of_district_<%= spot.district_id %>">
              <%= check_box_tag "transport[spot_ids][]", spot.id, @transport.spots.include?(spot), :prev_checked => @transport.spots.include?(spot), :id => dom_id(spot) %>

              <label for="<%= dom_id(spot) %>"><%= spot.name %></label>
            </div>
        <% end %>
      </div>
    </div>


    <div class="item_form_row">
      <div class="label">
        <%= t('general.label.image') %>

      </div>

      <div class="photo_box">
        <!-- <h3>Images <span style="font-size: 11px;"><%#= transport_photo_number_str(@transport) %></span></h3>-->
        <div class="edit_img_row">

          <% unless @transport.new_record? %>
              <%= render :partial => 'shared_partials/existing_photo', :collection => @transport.assets %>
          <% end %>

          <div id="transport_photos">
            <%= render :partial => 'shared_partials/photo', :locals => {:form => f, :photo => @transport.assets.new} if @transport.new_record? %>
          </div>

        </div>
        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreImage' %>
      </div>

    </div>


    <div class="item_form_row">
      <div class="label wider">
        <%= t('general.label.branches') %>

      </div>


      <div class="f_edit_row photo_box" style="width:705px;">


        <div id="transport_branch_locations" class="package_events">

          <% unless @transport.new_record? %>
              <%= render :partial => 'shared_partials/branch_location', :collection => @transport.branch_locations, :locals => {:form => f} %>
          <% end %>
          <%= render :partial => 'shared_partials/branch_location', :locals => {:form => f, :branch_location => @transport.branch_locations.new} if @transport.new_record? || @transport.branch_locations.size == 0 %>
        </div>

        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreBranchLocation' %>
      </div>

    </div>

    <div class="item_form_row">
      <div class="label wider">
        <%= t('general.label.schedule') %>

      </div>

      <div class="f_edit_row photo_box" style="width:705px;">


        <div id="transport_departure_schedules" class="package_events">

          <% unless @transport.new_record? %>
              <%= render :partial => 'departure_schedule', :collection => @transport.departure_schedules, :locals => {:form => f} %>
          <% end %>
          <%= render :partial => 'departure_schedule', :locals => {:form => f, :departure_schedule => @transport.departure_schedules.new} if @transport.new_record? || @transport.departure_schedules.size == 0 %>
        </div>

        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreDepartureSchedule' %>
      </div>

    </div>


    <div class="item_form_row">
      <div class="label ">
        <%= t('general.label.policies') %>

      </div>

      <div class="f_edit_row photo_box" style="width:705px;">


        <div id="transport_policies" class="package_events">

          <% unless @transport.new_record? %>
              <%= render :partial => 'shared_partials/policy', :collection => @transport.policies, :locals => {:form => f} %>
          <% end %>
          <%= render :partial => 'shared_partials/policy', :locals => {:form => f, :policy => @transport.policies.new} if @transport.new_record? || @transport.policies.size == 0 %>
        </div>

        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMorePolicy' %>
      </div>

    </div>

    <div class="item_form_row">
      <div class="label ">
        <%= t('general.label.contacts') %>

      </div>

      <div class="f_edit_row photo_box" style="width:705px;">


        <div id="transport_contacts" class="package_events">

          <% unless @transport.new_record? %>
              <%= render :partial => 'shared_partials/contact', :collection => @transport.contacts, :locals => {:form => f} %>
          <% end %>
          <%= render :partial => 'shared_partials/contact', :locals => {:form => f, :contact => @transport.contacts.new} if @transport.new_record? || @transport.contacts.size == 0 %>
        </div>

        <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreContact' %>
      </div>

    </div>


    <div class="submit_btn">
      <%= f.submit :class => 'search_button', :style => 'width:140px' %>
      <span class="search_button_right"> </span>
    </div>


<% end %>
<div style="display:none">
  <div id="new_photo_html">
    <%= render(:partial => 'shared_partials/photo', :locals => {:form => @builder}, :object => @transport.assets.new) %>
  </div>


  <div id="new_contact_html">
    <%= render(:partial => 'shared_partials/contact', :locals => {:form => @builder}, :object => @transport.contacts.new) %>
  </div>

  <div id="new_policy_html">
    <%= render(:partial => 'shared_partials/policy', :locals => {:form => @builder}, :object => @transport.policies.new) %>
  </div>

  <div id="new_departure_schedule_html">
    <%= render(:partial => 'departure_schedule', :locals => {:form => @builder}, :object => @transport.departure_schedules.new) %>
  </div>

  <div id="new_branch_location_html">
    <%= render(:partial => 'shared_partials/branch_location', :locals => {:form => @builder}, :object => @transport.branch_locations.new) %>
  </div>

  <%= render :partial => 'shared_partials/edit_asset_label' %>
</div>


<style type="text/css">


</style>
<script type="text/javascript">
    var allowed_images = 10;

    $(document).ready(function() {
        TBD.DHTML.addMoreItem('a.addMoreContact', '#new_contact_html', '#transport_contacts', 'span.removeContactField', 'contact');
        TBD.DHTML.addMoreItem('a.addMorePolicy', '#new_policy_html', '#transport_policies', 'span.removePolicyField', 'policy');
        TBD.DHTML.addMoreItem('a.addMoreBranchLocation', '#new_branch_location_html', '#transport_branch_locations', 'span.removeBranchLocationField', 'branch_location');
        TBD.DHTML.addMoreItem('a.addMoreDepartureSchedule', '#new_departure_schedule_html', '#transport_departure_schedules', 'span.removeDepartureScheduleField', 'departure_schedule');
        TBD.DHTML.addMoreItem('a.addMoreDestination', '#new_destination_html', '#transport_destinations', 'span.removeDestinationField', 'destination');

        var validator = $("#transport_form").validate({
            invalidHandler: function() {
                $("#summary").html('<div class="item_form_row">' + TBD.GENERAL.translateNumber(validator.numberOfInvalids(), '<%=I18n.locale%>') + " <%= t('general.label.invalid_form_fields')%></div>");
                //$('textarea.tiny_redcloth').removeAttr('trc_option_enabled');
                //$('textarea.tiny_redcloth').tinyRedcloth();

            },
            errorPlacement: function(error, element) {
                error.remove();
            },

            rules: {
                'transport[category_id]': "required",
                'transport[name]' : "required",
                'transport[description]': "required"
            },
            messages: {
                comment: "Please enter a comment."
            }
        });

        $('#transport_discount_till, #transport_start_date, #transport_end_date').datepicker({
            changeMonth: true,
            changeYear: true
        });

        TBD.DHTML.addMorePhoto('transport_photos', allowed_images);
        TBD.ASSETS.deleteAsset('transports');
        TBD.ASSETS.makeMainPhoto('transports');

        $(".district_in_transport input[type='checkbox']").each(function () {
            TBD.DHTML.checkUncheckSpot(this);
        });
        $(".district_in_transport input[type='checkbox']").click(function () {
            TBD.DHTML.checkUncheckSpot(this);
        });

    });


</script>

app/views/transports/edit.html.erb
<%= render 'form' %>

app/views/transports/index_admin.html.erb
<h1 class="admin_header">Listing Ads</h1>
<div class="admin_new_link"><%= link_to 'New Ad', new_ad_path(:f => true) %></div>

<div class="msg_desc_info_big">

  <div class="f_bor evenRow ">
    <div class="fl w_200 pad_lr_5">
      <strong><%= t('general.label.title')%></strong>
    </div>
    <div class="fl w_130 pad_lr_5">
      <strong>Category</strong>
    </div>
    <div class="fl w_130 pad_lr_5">
      <strong>Featured/Basic</strong>
    </div>
    <div class="admin_links">

    </div>
  </div>

  <% @packages.each do |ad| %>

      <div class="f_bor <%= cycle('oddROw', 'evenRow') %> ">
        <div class="fl w_200 pad_lr_5">
          <%= ad.title %>

        </div>

        <div class="fl w_130 pad_lr_5">
          <%= ad.category %>
        </div>
        <div class="fl w_130 pad_lr_5">
          <%= ad.featured ? 'Featured' : 'Basic' %>
        </div>


        <div class="fl admin_links">
          <span><%= link_to 'Show', package_path(ad) %></span>
          <span><%= link_to 'Edit', edit_package_path(ad) %></span>
          <span><%= link_to 'Destroy', package_path(ad), :confirm => 'Are you sure?', :method => :delete %></span>
        </div>
      </div>

  <% end %>

</div>

app/views/transports/new.html.erb
  <%= render 'form' %>

app/views/transports/plan.html.erb
<%= content_for :over_mid_content do %>
    <div class="redhead_row">
      <h2>Select Package</h2>
    </div>
<% end %>
<div class="selectPage">
  <div class="basicAd">
    <div class="basic_left"></div>
    <div class="basic_mid">
      <div class="basic_head">Basic Ad</div>
      <div class="basic_desc">
        includes :
        <ul>
          <li>7 Photos</li>
          <li>Access to marketing tools</li>
          <li>A great way to test the online market for your ad.</li>
        </ul>
      </div>
      <div class="b_price basic_desc">
        $4.95
        <span>For 3 months</span>
      </div>
      <%= link_to 'Choose Package', 'javascript:void(0)', :class =>'choose_btn', :location => new_ad_path(:f=>0) %>
    </div>
    <div class="basic_right"></div>
  </div>

  <div class="mostPop">
    <div class="most_left"></div>
    <div class="most_mid">
      <div class="most_head">Featured
        <span>MOST POPULAR</span>
      </div>
      <div class="most_desc">
        includes :
        <ul>
          <li>15 Photos + 2 video links</li>
          <li>Featured on our homepage</li>
          <li>Listed on our monthly newsletter</li>
          <li>Access to marketing tools</li>
          <li>Promote your ad promotion packet</li>
          <li>Excellent Success Rate</li>
        </ul>
      </div>
      <div class="b_price most_desc">
        $9.95
        <span>For 6 months</span>
      </div>
      <div class="f_chose_btn">
        <%= link_to 'Choose Package', 'javascript:void(0)', :class =>'choose_btn', :location => new_ad_path(:f=>true) %>
      </div>

    </div>
    <div class="most_right"></div>
  </div>
</div>

<script type="text/javascript">


    $(document).ready(function() {
        $('a.choose_btn').click(function() {
            location.href = $(this).attr('location');
        });
    });


</script>

app/views/transports/show.html.erb
<% title @transport.name %>
<%= content_for :js_css_include do %>
    <script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2&key=<%= GMAP_API_KEY %>"></script>

    <%= javascript_include_tag 'jquery.easing.1.3', 'jquery.galleryview-1.1', 'jquery.timers-1.1.2', 'thickbox', 'jquery.gmap-1.1.0-min' %>
    <%= javascript_include_tag 'jquery.validate' %>
    <%= stylesheet_link_tag 'thickbox' %>

<% end %>

<%= content_for :over_mid_content do %>
    <div class="redhead_row">
      <div class="subLink">
        <ul>
           <% if can_edit?(@transport) %>
              <li>
                <%= link_to t('general.label.edit'), edit_transport_path(@transport) %>
              </li>
          <% end %>
          <li>
            <%= link_to t('general.label.message_to_authority'), "#TB_inline?dd=4&width=400&height=400&inlineId=send_message_to_owner_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('general.label.tell_your_friends'), "#TB_inline?dd=4&width=400&height=300&inlineId=send_to_friend_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('helpers.submit.print'), print_transport_path(@transport) %>
          </li>
          <li id="saved_item_li">
            <%= render :partial => 'shared_partials/saved_item', :locals => {:savable => @transport} %>
          </li>
          <li>
             <%= link_to t('general.label.own_this', :item => @transport.class.name),  "#TB_inline?dd=4&width=400&height=500&inlineId=ownership_request_lb&modal=true", :class => 'thickbox', :title => t('general.label.own_this_hints') %>
          </li>
        </ul>
      </div>
    </div>
<% end %>

<div class="pageHead">
  <%= @transport.name %>
</div>

<%= render :partial => 'shared_partials/detail_page_photo_gallery', :locals => {:items => @transport.assets} %>

<div class="item_details">

  <div class="itemDetail pad_TL0"><%= @transport.description %></div>

  <div class="good_item_head">
    <%= t('general.label.branches') %>
  </div>
  <div class="itemDetail" style="width:682px;">

    <% @transport.locations_by_districts.each do |district, locations| %>
        <div class="eventTitle">
          <%= district.name  if district%>
        </div>
        <div class="branchLocations">
          <% branch_location_index = -1 %>
          <% locations.each do |location| %>
              <% branch_location_index += 1 %>
              <div class="branchLocation <%= 'clear' if branch_location_index % 3 == 0 %>">
                <span><b><%= location.location %></b></span>
                <span><%= t('general.label.address')%>: <%= location.address %></span>
                <span><%= t('general.label.phone')%>: <%= location.phone %></span>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.schedule') %>
  </div>
  <div class="itemDetailDeparture">
    <%= raw departure_schedules(@transport) %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.policies') %>
  </div>
  <div class="itemDetail">
    <% @transport.policies.each do |policy| %>
        <div class="eventTitle clear"><b><%= policy.title %></b></div>
        <div class="eventDetail clear"><%= policy.detail %></div>
    <% end %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.contacts') %>
  </div>
  <div class="itemDetail">
    <% @transport.contacts.each do |contact| %>
        <div class=" clear"><b><%= contact.name %></b></div>
        <div class="eventDetail clear"><%= t('general.label.phone')%>: <%= contact.phone %></div>
    <% end %>
  </div>



  <%= render :partial => 'shared_partials/detail_page_comment', :locals => {:item => @transport, :rating => true} %>
</div>

<div id="send_message_to_owner_lb" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb', :id => 'close_send_message_to_owner_lb', :title => 'close' %>
  <%= render :partial => 'messages/ajax_form', :locals => {:message_target => @transport} %>

</div>

<%= render :partial => 'shared_partials/send_to_friends', :locals => {:item => 'transport', :item_id => @transport.id} %>
<%= render :partial => 'shared_partials/ownership_request', :locals => {:item => 'transport', :item_id => @transport.id} %>


<style type="text/css">
    .branchLocations {
        width: 100%;
        float: left;
        margin-bottom: 10px;
    }

    .branchLocation {
        width: 217px;
        float: left;
        margin: 5px 10px 10px 0;
    }

    .branchLocation span {
        float: left;
        width: 217px;
    }

    div.departure_times {
        width: 680px;
        float: left;
    }

    span.departure_time {
        width: 100px;
        float: left;
        margin: 5px 10px 5px 0
    }

    .itemDetailDeparture {
        width: 702px;
        float: left;
        margin: 10px 0;
    }

    .itemDetailDeparture .evenRow, .itemDetailDeparture .oddRow {
        width: 682px;
        padding: 5px 10px;
        margin-bottom: 10px;
    }

    .itemDetailDeparture .evenRow {
        background: none;
        color: #000000;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#detail_page_photo_gallery').galleryView(TBD.DETAIL_PAGE_PHOTO_GALLERY_OPTIONS);
    });


</script>