config/routes.rb
Travelobd::Application.routes.draw do

  resources :ownership_requests do
    member do
      get :accept
    end
  end

  resources :club_joining_requests do
    member do
      post :approve
      post :deny
    end
  end

  resources :tour_clubs do
    resources :comments
    collection do
      get :search
    end

    member do
      get :print
      post :rate
      post :join_leave
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'users#failure'

  resources :authentications

  resources :tour_operators do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :transports do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :rooms

  resources :password_reset

  resources :profiles

  resources :hotels do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_spots
    end
    member do
      get :print
      post :rate
    end
  end

#

  resources :packages do
    resources :comments

    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :location_autocomplete
      get :load_cities
    end
    member do
      get :print
      post :rate
    end
  end

  resources :messages

  resources :spots do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_nearby_spots
    end
    member do
      get :print
      post :rate
    end
  end

  resources :elements

  resources :articles do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end
    member do
      get :print
      post :rate
    end
  end

  resources :profiles do
    member do
      get :spots
      get :articles
    end
  end

  resource :user_session
  resources :users do
    collection do
      post :save_item
      post :remove_saved_item
      get :load_uploaded_images
      post :upload_images
    end
    resource :profile
  end

  get "welcome/index"
  get "welcome/load_districts"
  get "users/dashboard"


  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  #match 'checkout' => 'carts#show'
  root :to => "welcome#index"

  #ajax on home page
  get 'welcome/articles'
  get 'welcome/other_classifieds'
  get 'welcome/featured_ads'
  get 'welcome/spots'


  match 'advance_search' =>'ads#advance_search'


  #dashboard
  match 'dashboard' => 'users#dashboard'
  match 'inbox' => 'users#inbox'
  match 'outbox' => 'users#outbox'
  match 'my_saved_listings' => 'users#saved_listings'
  match 'my_spots' => 'users#spots'
  match 'my_packages' => 'users#packages'
  match 'my_hotels' => 'users#hotels'
  match 'my_rooms' => 'users#rooms'
  match 'my_transports' => 'users#transports'
  match 'my_clubs' => 'users#clubs'
  match 'my_articles' => 'users#articles'
  match 'my_tour_operators' => "users#tour_operators"
  match 'send_to_friends' => 'users#send_to_friends'
  match 'club_leaving_requests' => 'club_joining_requests#leaving_requests'


  #newly added
  match 'tell_friends' => 'users#tell_friends'

  post 'assets/update_label', :as => :update_asset_label

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer(4)      not null, primary key
#  user_id     :integer(4)
#  active      :boolean(1)      default(FALSE)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer(4)
#

class Article < ActiveRecord::Base
  translates :title, :detail
  default_scope order('articles.created_at DESC')

  has_friendly_id :title, :use_slug => true
  has_many :assets, :as => :assetable, :dependent => :destroy
  has_one :main_image, :class_name => 'Asset', :as => :assetable, :conditions => {:main => true}
  validates :title, :presence => true

  belongs_to :user
  has_many :saved_listings, :as => :savable, :dependent => :destroy


  has_many :polymorphic_categories, :as => :categorizable, :dependent => :destroy
  has_many :categories, :through => :polymorphic_categories, :dependent => :destroy

  accepts_nested_attributes_for :assets, :reject_if => :all_blank, :allow_destroy => true

  acts_as_taggable
  has_many :comments, :as => :commentable
  has_many :approved_comments, :as => :commentable, :class_name => 'Comment', :conditions => {:approved => true}

  ajaxful_rateable :stars => 5, :allow_update => false, :dimensions => [:useful]

  def main_image_url(style = :medium)
    main_image ? main_image.photo.url(style) : assets.size > 0 ? assets.first.photo.url(style) : ''
  end

  def category
    categories.collect(&:title).join(',')
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ResourcesController
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :require_user, :only =>[:new, :edit, :create, :update]
  before_filter :require_admin_user, :only =>[:destroy]
  before_filter lambda { @active_nav = 'articles' }
  before_filter :load_item, :only =>[:show, :edit, :update, :destroy, :print]
  before_filter :check_ownership, :only => [:edit, :update, :destroy]


#  uses_tiny_mce :only =>[:new, :edit],:options => {
#    :width => '445px',
#    :height => '250px'
#  }

  # GET /articles
  # GET /articles.xml
  def index
    conditions = []
    conditions.add_condition!(:category_id =>params[:category_id]) unless params[:category_id].blank?
    @articles = Article.paginate(:page=> params[:page], :per_page => 15, :conditions => conditions)
    #@search_title = Article::CATEGORIES.invert[params[:category_id].to_i] || 'All Articles'
    @search_title = 'All Articles'
    render :action => 'index_admin', :layout => 'admin' if admin?
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new(:category_id =>params[:category_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => t('general.label.item_created', :item => t('activerecord.models.article'))) }
        format.xml { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => t('general.label.item_update', :item => t('activerecord.models.article'))) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    if (admin? || @article.user_id == current_user.id)
      @article.destroy
    end

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml { head :ok }
    end
  end

  def delete_asset
      asset = Asset.find(params[:asset_id])
      asset.destroy
      render :nothing => true
    end

    def set_main_photo
      asset = Asset.find(params[:asset_id])
      Asset.update_all ['main = ?', false], ['assetable_type = ? AND assetable_id = ?', 'Article', asset.assetable_id]
      asset.update_attribute(:main, true)
      render :nothing => true
    end


  def search
    search_obj = Article.search(params[:search])
    ordering = "created_at DESC"
    @articles = search_obj.order(ordering).paginate(:page=> params[:page], :per_page => 15)
    @search_label = params[:label] || 'Articles : Search Results '
  end

  def print
    render :layout => 'print'
  end

  private
  def load_item
    @article = Article.find(params[:id])
  end

  def check_ownership
    ownership_require(@article)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/views/articles/_existing_photo.html.erb
<div class="edit_box_img existing_image">
  <div class="e_bor">
    <%= image_tag existing_photo.photo.url(:thumb) %>
  </div>
  <%= link_to 'Delete Photo', 'javascript:void(0)', :asset_id => existing_photo.id, :class => 'del_photo' %>
  <%= check_box_tag "main_check_#{existing_photo.id}", existing_photo.id, existing_photo.main?, :asset_id =>existing_photo.id, :class=> 'mainCh' %>
  Main Photo
</div>

app/views/articles/_form.html.erb
<% title localized_item_header(@article) %>
<div class="pageHead">
  <%= localized_item_header(@article) %>
</div>
<%= content_for :js_css_include do %>
    <%= javascript_include_tag 'jquery.form', 'jquery.validate', 'bangla.input', 'bangla_key_maps', 'tiny_redcloth', 'thickbox', 'jquery-fieldselection', 'jquery.caret.min' %>
    <%= stylesheet_link_tag 'jquery-ui', 'autocomplete', 'thickbox' %>
<% end %>
<div class="item_form">
  <%= form_for(@article, :html=> {:multipart => true, :id=> 'article_form'}) do |f| %>
      <% @builder = f %>
      <%= error_messages_for(@article) %>

      <div class="form_summary" id="summary"></div>

      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.category') %>
          <span>*</span>
        </div>
        <div class="f_edit_row photo_box">
          <% for category in Category.article_categories %>
              <div class="spot_in_package district_in_transport">
                <%= check_box_tag "article[category_ids][]", category.id, @article.categories.include?(category), :id => dom_id(category) %>

                <label for="<%= dom_id(category) %>"><%= category.title %></label>
              </div>
          <% end %>
        </div>
      </div>

      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.title') %>
          <span>*</span>
        </div>
        <%= f.text_field :title, :class=> 'txt' %>
      </div>


      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.details') %>
          <span>*</span>
        </div>
        <%= f.text_area :detail, :class => "tiny_redcloth" %>
      </div>

      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.tag') %>
        </div>
        <%= f.text_field :tag_list, :class=> 'txt' %>
      </div>


      <div class="submit_btn">
        <%= f.submit :class => 'search_button' %>
        <span class="search_button_right"> </span>
      </div>

  <% end %>
</div>
<%= render :partial => 'shared_partials/tiny_redcloth_image' %>


<script type="text/javascript">

    var allowed_images = 5;

    $(document).ready(function() {
        var validator = $("#article_frm").validate({
            invalidHandler: function() {
                $("#summary").html('<div class="item_form_row">' + TBD.GENERAL.translateNumber(validator.numberOfInvalids(), '<%=I18n.locale%>') + " <%= t('general.label.invalid_form_fields')%></div>");
            },
            errorPlacement: function(error, element) {
                error.remove();
            },


            rules: {
                'article[category_id]': "required",
                'article[title]' : "required",
                'article[detail]' : "required"

            },
            messages: {
                comment: "Please enter a comment."
            }
        });

        //TBD.DHTML.addMorePhoto('article_photos', allowed_images);
        //TBD.ASSETS.deleteAsset('articles');
        //TBD.ASSETS.makeMainPhoto('articles');
        $('#article_title').banglaInput();
        $('#article_tag_list').banglaInput();
        $('#article_detail').banglaInput();
        $('textarea.tiny_redcloth').tinyRedcloth();
    });


</script>

app/views/articles/_photo.html.erb
<div class="photo">

  <%= form.fields_for :assets, photo, :child_index => (photo.new_record? ? "index_to_replace_with_js" : nil) do |photo_form| %>
      <%= photo_form.file_field :photo, :class => 'photo' %>
      <span class="removeImageField"> <%= t('general.label.remove')%></span><br/>
  <% end %>

</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% title @search_title %>
<div class="pageHead">
  <%= t('activerecord.models.article') %>
  <div class="pageHeadOptions">

  </div>
</div>

<% @articles.each do |article| %>
    <div class="listItem">
      <div class="fl listItemLogo">
        <%= image_tag article.main_image_url(:thumb) %>
      </div>

      <div class="fl listItemDesc">
        <div class="fl hotel_desc_info">
          <div class="fl title">
            <%= link_to truncate(article.title, :length => 50), article %>
            <h4><%= article.category %></h4>
          </div>
          <div class="fl description">
            <%= truncate(sanitize(article.detail).gsub(/<\/?[^>]*>/, ""), :length => 350) %>
          </div>

        </div>
        <div class="fl price_n_button">
          <div class="fl">
            <div class="fl price">

            </div>

          </div>
          <%= link_to t('general.label.details'), article, :class => 'detail_link' %>
        </div>
      </div>

    </div>
<% end %>

app/views/articles/index_admin.html.erb
<h1 class="admin_header">Listing Articles</h1>
<div class="admin_new_link"><%= link_to 'New Article', new_article_path(:f => true) %></div>

<div class="msg_desc_info_big">

  <div class="f_bor evenRow ">
    <div class="fl w_300 pad_lr_5">
      <strong><%= t('general.label.title')%></strong>
    </div>
    <div class="fl w_130 pad_lr_5">
      <strong>Category</strong>
    </div>

    <div class="admin_links">

    </div>
  </div>

  <% @articles.each do |article| %>

      <div class="f_bor <%= cycle('oddROw', 'evenRow') %> ">
        <div class="fl w_300 pad_lr_5">
          <%= truncate(article.title, :length => 100) %>
        </div>

        <div class="fl w_130 pad_lr_5">
          <%= article.category %>
        </div>


        <div class="fl admin_links">
          <span><%= link_to 'Show', article %></span>
          <span><%= link_to 'Edit', edit_article_path(article) %></span>
          <span><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></span>
        </div>
      </div>

  <% end %>

</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/print.html.erb
<div class="pageHead">
  <%= @article.title %>
</div>

<div class="item_details">

  <div class="itemDetail pad_TL0">
    <%= raw textilize @article.detail %>
  </div>
</div>

app/views/articles/search.html.erb
<% title 'Search  Item' %>
<%= content_for :over_mid_content do %>
    <div class="redhead_row">
      <h2>
        <%= @search_label %>
      </h2>
    </div>
<% end %>

<div class="firms_row">
  <div class="firms_head">
    <%= @search_label %>
  </div>
  <% @articles.each do |article| %>
      <div class="f_bor directory <%= extra_css_class(article) %>">
        <div class="f_inner_bor">
          <%= link_to image_tag(article.main_image_url(:thumb), :width => 97, :height => 67), friendly_url(article) %>
        </div>
        <strong><%= article.category %></strong>

        <h3>
          <%= link_to article.title, friendly_url(article) %>
        </h3>

        <div>

          <%= truncate(sanitize(article.description).gsub(/<\/?[^>]*>/, ""), :length => 150) %>

        </div>

      </div>
  <% end %>
  <% if  @articles.respond_to?(:total_pages) && @articles.total_pages > 1 %>
      <div class="f_bor pagination">
        <%= will_paginate @articles %>
      </div>
  <% end %>
  <div class="firma_bottom"></div>
</div>

<style type="text/css">

    .f_inner_bor {
        height: 67px;
        width: 97px;
    }
</style>

app/views/articles/show.html.erb
<% title @article.title %>

<%= content_for :js_css_include do %>

    <%= javascript_include_tag 'thickbox' %>
    <%= javascript_include_tag 'jquery.validate' %>
    <%= stylesheet_link_tag 'thickbox' %>
    <%=raw meta_tags_for_fb(@article.title, 'Article', article_url(:id => @article.custom_friendly_id, :host => request.host),"http://#{request.host}#{@article.main_image_url(:thumb)}") %>
<% end %>
<%= content_for :over_mid_content do %>
    <div class="redhead_row">
      <div class="subLink">
        <ul>
          <% if can_edit?(@article) %>
              <li>
                <%= link_to t('general.label.edit'), edit_article_path(@article) %>
              </li>
          <% end %>
          <li>
            <%= link_to t('general.label.message_to_authority'), "#TB_inline?dd=4&width=400&height=400&inlineId=send_message_to_owner_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('general.label.tell_your_friends'), "#TB_inline?dd=4&width=400&height=300&inlineId=send_to_friend_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('helpers.submit.print'), print_article_path(@article) %>
          </li>
          <li id="saved_item_li">
            <%= render :partial => 'shared_partials/saved_item', :locals => {:savable => @article} %>
          </li>
        </ul>
      </div>
    </div>
<% end %>

<div class="pageHead">
  <%= @article.title %>
</div>

<div class="item_details">

  <div class="itemDetail pad_TL0">
    <%= raw textilize @article.detail %>
  </div>
  <div class="itemDetail clear">
    <fb:like href="<%= article_url(:id => @article.id, :host => request.host, :port => request.port) %>" layout="standard" show_faces="true" width="400" action="like" font="segoe ui" colorscheme="light"/>
  </div>

  <%= render :partial => 'shared_partials/detail_page_comment', :locals => {:item => @article, :rating => true} %>

</div>

<div id="send_message_to_owner_lb" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb', :id => 'close_send_message_to_owner_lb', :title => 'close' %>
  <%= render :partial => 'messages/ajax_form', :locals => {:message_target => @article} %>

</div>

<%= render :partial => 'shared_partials/send_to_friends', :locals => {:item => 'article', :item_id => @article.id} %>
<script type="text/javascript ">

    $(document).ready(function() {

    });


</script>