config/routes.rb
Travelobd::Application.routes.draw do

  resources :ownership_requests do
    member do
      get :accept
    end
  end

  resources :club_joining_requests do
    member do
      post :approve
      post :deny
    end
  end

  resources :tour_clubs do
    resources :comments
    collection do
      get :search
    end

    member do
      get :print
      post :rate
      post :join_leave
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'users#failure'

  resources :authentications

  resources :tour_operators do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :transports do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end

    member do
      get :print
      post :rate
    end
  end

  resources :rooms

  resources :password_reset

  resources :profiles

  resources :hotels do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_spots
    end
    member do
      get :print
      post :rate
    end
  end

#

  resources :packages do
    resources :comments

    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :location_autocomplete
      get :load_cities
    end
    member do
      get :print
      post :rate
    end
  end

  resources :messages

  resources :spots do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
      get :load_nearby_spots
    end
    member do
      get :print
      post :rate
    end
  end

  resources :elements

  resources :articles do
    resources :comments
    collection do
      post :delete_asset
      post :set_main_photo
      get :search
    end
    member do
      get :print
      post :rate
    end
  end

  resources :profiles do
    member do
      get :spots
      get :articles
    end
  end

  resource :user_session
  resources :users do
    collection do
      post :save_item
      post :remove_saved_item
      get :load_uploaded_images
      post :upload_images
    end
    resource :profile
  end

  get "welcome/index"
  get "welcome/load_districts"
  get "users/dashboard"


  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  #match 'checkout' => 'carts#show'
  root :to => "welcome#index"

  #ajax on home page
  get 'welcome/articles'
  get 'welcome/other_classifieds'
  get 'welcome/featured_ads'
  get 'welcome/spots'


  match 'advance_search' =>'ads#advance_search'


  #dashboard
  match 'dashboard' => 'users#dashboard'
  match 'inbox' => 'users#inbox'
  match 'outbox' => 'users#outbox'
  match 'my_saved_listings' => 'users#saved_listings'
  match 'my_spots' => 'users#spots'
  match 'my_packages' => 'users#packages'
  match 'my_hotels' => 'users#hotels'
  match 'my_rooms' => 'users#rooms'
  match 'my_transports' => 'users#transports'
  match 'my_clubs' => 'users#clubs'
  match 'my_articles' => 'users#articles'
  match 'my_tour_operators' => "users#tour_operators"
  match 'send_to_friends' => 'users#send_to_friends'
  match 'club_leaving_requests' => 'club_joining_requests#leaving_requests'


  #newly added
  match 'tell_friends' => 'users#tell_friends'

  post 'assets/update_label', :as => :update_asset_label

end

app/models/tour_operator.rb
class TourOperator < ActiveRecord::Base
  translates :name, :description, :address
  default_scope order('tour_operators.created_at DESC')


  has_attached_file :logo, :styles => {:medium => "400x300", :thumb => "80x70>"},
                    :url => "/assets/tour_operators_logo/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/tour_operators_logo/:id/:style/:basename.:extension"

  has_many :packages

  has_many :polymorphic_categories , :as => :categorizable, :dependent => :destroy
  has_many :categories, :through => :polymorphic_categories , :dependent => :destroy

  belongs_to :user
  has_many :contacts, :as => :contactable
  has_many :services, :class_name => 'TitleDetailAttribute', :as => :td_attributable, :conditions => {:td_association_type => :service}
  has_many :policies, :as => :policiable
  has_many :comments, :as => :commentable
  has_many :approved_comments, :as => :commentable, :class_name => 'Comment', :conditions => {:approved => true}
  has_one :ownership_request, :as => :resource
  has_many :saved_listings, :as => :savable, :dependent => :destroy
  has_and_belongs_to_many :destinations, :class_name => "District"
  has_and_belongs_to_many :spots

  has_friendly_id :name, :use_slug => true

  validates :name, :presence =>  true
  validates :address, :presence =>  true

  accepts_nested_attributes_for :contacts, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :policies, :reject_if => lambda { |a| a[:detail].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :services, :reject_if => lambda { |a| a[:detail].blank? }, :allow_destroy => true


  ajaxful_rateable :stars => 5, :allow_update => false, :dimensions => [:useful, :price]

  CATEGORIES = {'cat1' => 1, 'cat2' => 2, 'cat3' => 3}
  scope :featured #, where(:featured => true)

  def category
    categories.collect(&:title).join(',')
  end

  class << self
    def mine(user)
       where(:user_id => user.id)
    end
  end
end

app/controllers/admin/tour_operators_controller.rb
class Admin::TourOperatorsController < Admin::ResourcesController
end

app/controllers/tour_operators_controller.rb
class TourOperatorsController < ApplicationController
  before_filter :require_user, :only=> [:new, :edit, :create, :update, :destroy]
  before_filter lambda { @active_nav = 'tour_operators' }
  before_filter :load_item, :only =>[:show, :edit, :update, :destroy, :print, :rate]
  before_filter :check_ownership, :only => [:edit, :update]
  before_filter :check_if_owner, :only => [:destroy]
  layout :choose_layout
  # GET /ads
  # GET /ads.xml
  def index
    @tour_operators = TourOperator.paginate(:page=> params[:page], :per_page => 15)
    @paginate_items = @tour_operators
    render :action => 'index_admin', :layout => 'admin' if admin?
  end

  # GET /ads/1
  # GET /ads/1.xml
  def show
    @already_saved = SavedListing.in_my_list(current_user.id, @tour_operator.id, 'TourOperator') if current_user
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @tour_operator }
    end
  end

  # GET /ads/new
  # GET /ads/new.xml
  def new
    @tour_operator = TourOperator.new
    @return_to_package = params[:return_to_package]
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.xml
  def create
    @tour_operator = TourOperator.new(params[:tour_operator])
    @tour_operator.user_id = current_user.id
    respond_to do |format|
      if @tour_operator.save
        unless params[:return_to_package].blank?
          format.html { redirect_to(new_package_path(:tour_operator_id => @tour_operator), :notice => t('general.label.item_created', :item => t('activerecord.models.tour_operator'))) }
        else
          format.html { redirect_to(@tour_operator, :notice => t('general.label.item_created', :item => t('activerecord.models.tour_operator'))) }
        end
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @tour_operator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.xml
  def update
    params[:tour_operator][:destination_ids] ||= []
    respond_to do |format|
      if @tour_operator.update_attributes(params[:tour_operator])
        format.html { redirect_to(@tour_operator, :notice => t('general.label.item_update', :item => t('activerecord.models.tour_operator'))) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @tour_operator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.xml
  def destroy
    @tour_operator.destroy

    respond_to do |format|
      format.html { redirect_to(tour_operators_url) }
      format.xml { head :ok }
    end
  end

  def delete_asset
      asset = Asset.find(params[:asset_id])
      asset.destroy
      render :nothing => true
    end

    def set_main_photo
      asset = Asset.find(params[:asset_id])
      Asset.update_all ['main = ?', false], ['assetable_type = ? AND assetable_id = ?', 'TourOperator', asset.assetable_id]
      asset.update_attribute(:main, true)
      render :nothing => true
    end




  def location_autocomplete
    districts = District.includes(:division).where(['districts.name like ?  OR divisions.name like ?', "%#{params[:term]}%", "%#{params[:term]}%"]).limit(15)
    render :json => districts.collect { |c| {"id" => c.id, "label" => "#{c.name}, #{c.division.name if c.division}", "value" => c.name} }
  end


  def search
    @tour_operator_search = TourOperator.search(params[:search])
    @tour_operators = @tour_operator_search.paginate(:page=> params[:page], :per_page => 15)
    @search_label = params[:label] || 'TourOperators : Search Results '
    @paginate_items = @tour_operators
    render :index
  end


  def print
    render :layout => 'print'
  end

  def rate
    @tour_operator.rate(params[:stars], current_user, params[:dimension])
    respond_to do |format|
      format.js { render :partial => '/comments/rate', :locals => {:obj => @tour_operator} }
    end

  end


  private

  def load_item
    @tour_operator = TourOperator.find(params[:id])
  end

  def check_ownership
    current_user && (current_user.id == @tour_operator.user_id || OwnershipRequest.owned('TourOperator', current_user.id).collect(&:resource_id).include?(@tour_operator.id))
  end

  def check_if_owner
    ownership_require(@tour_operator)
  end

  def choose_layout
    ['new', 'edit'].include?(action_name) ? 'dashboard' : 'application'
  end
end

app/helpers/tour_operators_helper.rb
module TourOperatorsHelper
end

app/views/tour_operators/_destination.html.erb
<div class="destination">
  <%= form.fields_for :destinations, destination, :child_index => (destination.new_record? ? "index_to_replace_with_js" : nil) do |destination_form| %>
      <%= destination_form.select 'destination_ids[]', District.all_active %>
  <% end %>
</div>

app/views/tour_operators/_form.html.erb
<% title localized_item_header(@tour_operator) %>
<div class="pageHead">
  <%= localized_item_header(@tour_operator) %>
</div>

<%= content_for :js_css_include do %>
    <%= javascript_include_tag 'jquery.validate', 'thickbox' %>
    <%= stylesheet_link_tag 'jquery-ui', 'autocomplete', 'thickbox' %>
<% end %>
<div class="item_form">
  <%= form_for(@tour_operator, :html => {:multipart => true, :id=> 'tour_operator_form'}) do |f| %>
      <% @builder = f %>

      <%= error_messages_for(@tour_operator) %>

      <div class="form_summary" id="summary">
      </div>

      <div class="item_form_row">
        <div class="label">
          <%= f.label :category_id, t('general.label.category') %>
          <span>*</span>
        </div>
        <div class="f_edit_row photo_box">
          <% for category in Category.tour_operator_categories %>
              <div class="spot_in_package district_in_transport">
                <%= check_box_tag "tour_operator[category_ids][]", category.id, @tour_operator.categories.include?(category), :id => dom_id(category) %>

                <label for="<%= dom_id(category) %>"><%= category.title %></label>
              </div>
          <% end %>
        </div>
      </div>

      <div class="item_form_row">
        <div class="label">
          <%= f.label :name, t('general.label.name') %>
          <span>*</span>
        </div>
        <%= f.text_field :name %>
      </div>
      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.address') %>
          <span>*</span>
        </div>
        <%= f.text_area :address, :class => 'address' %>
      </div>

      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.logo') %>
          </div>
        <%= f.file_field :logo %>
      </div>


      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.description') %>
          <span>*</span>
          </div>

        <%= f.text_area :description, :rows => 20, :cols => 80 %>
      </div>


      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.website') %>
          </div>

        <%= f.text_field :web %>
      </div>


      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.destinations') %>
          </div>

        <div class="f_edit_row photo_box">
          <% for district in District.actives %>
              <div class="spot_in_package district_in_tour_operator">
                <%= check_box_tag "tour_operator[destination_ids][]", district.id, @tour_operator.destinations.include?(district), :id => dom_id(district) %>

                <label for="<%= dom_id(district) %>"><%= district.name %></label>
              </div>
          <% end %>
        </div>


      </div>
      <div class="item_form_row">
       <div class="label">
          <%= t('general.label.spots') %>
          </div>

        <div class="f_edit_row photo_box">
          <% for spot in Spot.actives.includes(:district) %>
              <div class="spot_in_package spot_of_district_<%= spot.district_id %>">
                <%= check_box_tag "tour_operator[spot_ids][]", spot.id, @tour_operator.spots.include?(spot), :prev_checked => @tour_operator.spots.include?(spot), :id => dom_id(spot) %>

                <label for="<%= dom_id(spot) %>"><%= spot.name %></label>
              </div>
          <% end %>
        </div>
      </div>


      <div class="item_form_row">
       <div class="label">
          <%= t('general.label.services') %>
          </div>

        <div class="f_edit_row photo_box" style="width:705px;">
          <div id="tour_operator_services" class="package_events">

            <% unless @tour_operator.new_record? %>
                <%= render :partial => 'service', :collection => @tour_operator.services, :locals => {:form => f} %>
            <% end %>
            <%= render :partial => 'service', :locals => {:form => f, :service => @tour_operator.services.new} if @tour_operator.new_record? || @tour_operator.services.size == 0 %>
          </div>

          <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreService' %>
        </div>
      </div>


      <div class="item_form_row">
       <div class="label">
          <%= t('general.label.policies') %>
          </div>

        <div class="f_edit_row photo_box" style="width:705px;">


          <div id="tour_operator_policies" class="package_events">

            <% unless @tour_operator.new_record? %>
                <%= render :partial => 'shared_partials/policy', :collection => @tour_operator.policies, :locals => {:form => f} %>
            <% end %>
            <%= render :partial => 'shared_partials/policy', :locals => {:form => f, :policy => @tour_operator.policies.new} if @tour_operator.new_record? || @tour_operator.policies.size == 0 %>
          </div>

          <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMorePolicy' %>
        </div>

      </div>


      <div class="item_form_row">
        <div class="label">
          <%= t('general.label.contacts') %>
          </div>

        <div class="f_edit_row photo_box" style="width:705px;">


          <div id="tour_operator_contacts" class="package_events">

            <% unless @tour_operator.new_record? %>
                <%= render :partial => 'shared_partials/contact', :collection => @tour_operator.contacts, :locals => {:form => f} %>
            <% end %>
            <%= render :partial => 'shared_partials/contact', :locals => {:form => f, :contact => @tour_operator.contacts.new} if @tour_operator.new_record? || @tour_operator.contacts.size == 0 %>
          </div>

          <%= link_to t('general.label.add_more'), 'javascript:void(0)', :class=>'adMore addMoreContact' %>
        </div>

      </div>


      <div class="submit_btn">
        <%= hidden_field_tag :return_to_package, @return_to_package  if @return_to_package%>
        <%= f.submit :class => 'search_button' %>
        <span class="search_button_right"> </span>
      </div>


  <% end %>
</div>
<div style="display:none">
  <div id="new_contact_html">
    <%= render(:partial => 'shared_partials/contact', :locals => {:form => @builder}, :object => @tour_operator.contacts.new) %>
  </div>

  <div id="new_policy_html">
    <%= render(:partial => 'shared_partials/policy', :locals => {:form => @builder}, :object => @tour_operator.policies.new) %>
  </div>

  <div id="new_service_html">
    <%= render(:partial => 'tour_operators/service', :locals => {:form => @builder}, :object => @tour_operator.services.new) %>
  </div>

  <%= render :partial => 'shared_partials/edit_asset_label' %>
</div>



<style type="text/css">


</style>
<script type="text/javascript">
    var allowed_images = 10;


    $(document).ready(function() {

        TBD.DHTML.addMoreItem('a.addMoreContact', '#new_contact_html', '#tour_operator_contacts', 'span.removeContactField', 'contact');
        TBD.DHTML.addMoreItem('a.addMorePolicy', '#new_policy_html', '#tour_operator_policies', 'span.removePolicyField', 'policy');
        TBD.DHTML.addMoreItem('a.addMoreService', '#new_service_html', '#tour_operator_services', 'span.removeServiceField', 'service');

        var validator = $("#tour_operator_form").validate({
            invalidHandler: function() {
                $("#summary").html('<div class="item_form_row">' + TBD.GENERAL.translateNumber(validator.numberOfInvalids(), '<%=I18n.locale%>') + " <%= t('general.label.invalid_form_fields')%></div>");
                //$('textarea.tiny_redcloth').removeAttr('trc_option_enabled');
                //$('textarea.tiny_redcloth').tinyRedcloth();

            },
            errorPlacement: function(error, element) {
                error.remove();
            },

            rules: {
                'tour_operator[category_id]': "required",
                'tour_operator[name]' : "required",
                'tour_operator[description]': "required"
            },
            messages: {
                comment: "Please enter a comment."
            }
        });

        $('#tour_operator_discount_till, #tour_operator_start_date, #tour_operator_end_date').datepicker({
            changeMonth: true,
            changeYear: true
        });

        $(".district_in_tour_operator input[type='checkbox']").click(function () {
            TBD.DHTML.checkUncheckSpot(this);
        });
        $(".district_in_tour_operator input[type='checkbox']").each(function () {
            TBD.DHTML.checkUncheckSpot(this);
        });


    });


</script>

app/views/tour_operators/_service.html.erb
<div class="event service">

  <%= form.fields_for :services, service, :child_index => (service.new_record? ? "index_to_replace_with_js" : nil) do |service_form| %>
      <div class="package_event_time">
        <%= t('general.label.name') %>
      </div>
      <div class="package_contact_address">
        <%= t('general.label.details') %>
        <%= t('general.label.if_list_style_required') %>
      </div>


      <div class="package_event_time clear">
        <%= service_form.text_field :title, :class => 'event' %>
      </div>

      <div class="package_contact_address">
        <%= service_form.text_area :detail, :class => 'event' %>
        <%= service_form.hidden_field :td_association_type, :value => :service, :class => 'event' %>
      </div>

      <div class="deleteLink">
        <% if service.new_record? %>
            <span class="removeCostItemField"> <%= t('general.label.remove') %></span>
        <% else %>
            <%= service_form.check_box :_destroy %>
            <span class="deleteLink deleteLinkCheckbox">
            <%= t('helpers.delete') %>
            </span>
        <% end %>
      </div>
  <% end %>

</div>

app/views/tour_operators/index.html.erb
<% title @search_title || 'Tour Operator list' %>

<div class="pageHead">
  <%= t('activerecord.models.tour_operator') %>
  <div class="pageHeadOptions">
   <!-- <b>Sort by: </b> <%= link_to 'Price', '#' %>-->
  </div>
</div>

<% @tour_operators.each do |tour_operator| %>
    <div class="listItem">
      <div class="fl listItemLogo">
        <%= image_tag tour_operator.logo.url() %>
      </div>

      <div class="fl listItemDesc">
        <div class="fl hotel_desc_info">
          <div class="fl title">
            <%= link_to truncate(tour_operator.name, :length => 50), tour_operator %>
            <h4><%= truncate(tour_operator.address, :length => 70) %></h4>
          </div>
          <div class="fl description">
            <%= truncate(sanitize(tour_operator.description).gsub(/<\/?[^>]*>/, ""), :length => 300) %>
          </div>

        </div>
        <div class="fl price_n_button">
          <div class="fl">
            <div class="fl price">

            </div>

          </div>
         <%= link_to t('general.label.details'), tour_operator, :class => 'detail_link' %>
        </div>
      </div>

    </div>
<% end %>

app/views/tour_operators/index_admin.html.erb
<h1 class="admin_header">Listing Ads</h1>
<div class="admin_new_link"><%= link_to 'New Ad', new_ad_path(:f => true) %></div>

<div class="msg_desc_info_big">

  <div class="f_bor evenRow ">
    <div class="fl w_200 pad_lr_5">
      <strong><%= t('general.label.title')%></strong>
    </div>
    <div class="fl w_130 pad_lr_5">
      <strong>Category</strong>
    </div>
    <div class="fl w_130 pad_lr_5">
      <strong>Featured/Basic</strong>
    </div>
    <div class="admin_links">

    </div>
  </div>

  <% @packages.each do |ad| %>

      <div class="f_bor <%= cycle('oddROw', 'evenRow') %> ">
        <div class="fl w_200 pad_lr_5">
          <%= ad.title %>
        </div>

        <div class="fl w_130 pad_lr_5">
          <%= ad.category %>
        </div>
        <div class="fl w_130 pad_lr_5">
          <%= ad.featured ? 'Featured' : 'Basic' %>
        </div>


        <div class="fl admin_links">
          <span><%= link_to 'Show', package_path(ad) %></span>
          <span><%= link_to 'Edit', edit_package_path(ad) %></span>
          <span><%= link_to 'Destroy', package_path(ad), :confirm => 'Are you sure?', :method => :delete %></span>
        </div>
      </div>

  <% end %>

</div>

app/views/tour_operators/print.html.erb
<div class="pageHead">
  <%= @tour_operator.name %>
</div>


<div class=" item_details ">

  <div class="itemDetail pad_TL0"><%= @tour_operator.description %></div>


  <div class="good_item_head">
    <%= t('general.label.services') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.services.each do |service| %>
        <div class="eventTitle clear"><b><%= service.title %></b></div>
        <div class="eventDetail clear"><%= raw textilize service.detail %></div>
    <% end %>
  </div>

  <div class="good_item_head">
     <%= t('general.label.policies') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.policies.each do |policy| %>
        <div class="eventTitle clear"><b><%= policy.title %></b></div>
        <div class="eventDetail clear"><%= policy.detail %></div>
    <% end %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.contacts') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.contacts.each do |contact| %>
        <div class=" clear"><b><%= contact.name %></b></div>
        <div class="eventDetail clear"><%= t('general.label.phone') %>: <%= contact.phone %></div>
    <% end %>
  </div>


</div>

app/views/tour_operators/show.html.erb
<% title @tour_operator.name %>

<%= content_for :js_css_include do %>
    <%= javascript_include_tag 'jquery.easing.1.3', 'jquery.galleryview-1.1', 'jquery.timers-1.1.2', 'thickbox' %>
    <%= javascript_include_tag 'jquery.validate' %>
    <%= stylesheet_link_tag 'thickbox' %>

<% end %>

<%= content_for :over_mid_content do %>
    <div class="redhead_row">
      <div class="subLink">
        <ul>
          <% if can_edit?(@tour_operator) %>
              <li>
                <%= link_to t('general.label.edit'), edit_tour_operator_path(@tour_operator) %>
              </li>
          <% end %>
          <li>
            <%= link_to t('general.label.message_to_authority'), "#TB_inline?dd=4&width=400&height=400&inlineId=send_message_to_owner_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('general.label.tell_your_friends'), "#TB_inline?dd=4&width=400&height=300&inlineId=send_to_friend_lb&modal=true", :class => 'thickbox' %>
          </li>

          <li>
            <%= link_to t('helpers.submit.print'), print_tour_operator_path(@tour_operator) %>
          </li>
          <li id="saved_item_li">
            <%= render :partial => 'shared_partials/saved_item', :locals => {:savable => @tour_operator} %>
          </li>
          <li>
             <%= link_to t('general.label.own_this', :item => @tour_operator.class.name),  "#TB_inline?dd=4&width=400&height=500&inlineId=ownership_request_lb&modal=true", :class => 'thickbox', :title => t('general.label.own_this_hints') %>
          </li>
        </ul>
      </div>
    </div>
<% end %>

<div class="pageHead">
  <%= @tour_operator.name %>
</div>


<div class=" item_details ">

  <div class="itemDetail pad_TL0"><%= @tour_operator.description %></div>


  <div class="good_item_head">
    <%= t('general.label.services') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.services.each do |service| %>
        <div class="eventTitle clear"><b><%= service.title %></b></div>
        <div class="eventDetail clear"><%= raw textilize service.detail %></div>
    <% end %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.policies') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.policies.each do |policy| %>
        <div class="eventTitle clear"><b><%= policy.title %></b></div>
        <div class="eventDetail clear"><%= policy.detail %></div>
    <% end %>
  </div>

  <div class="good_item_head">
    <%= t('general.label.contacts') %>
  </div>
  <div class="itemDetail">
    <% @tour_operator.contacts.each do |contact| %>
        <div class=" clear"><b><%= contact.name %></b></div>
        <div class="eventDetail clear"><%= t('general.label.phone') %>: <%= contact.phone %></div>
    <% end %>
  </div>
  <div class="good_item_head">
    <%= t('general.label.packages') %>
  </div>
  <div class="itemDetail">

    <ol>
      <%= render  :partial => 'packages/partial_package',:collection => @tour_operator.packages %>
    </ol>
  </div>

  <%#= render :partial => 'shared_partials/detail_page_comment', :locals => {:item => @tour_operator, :rating => true} %>


</div>




<div id="send_message_to_owner_lb" style="display: none">
  <%= image_tag 'close.jpeg', :class=> 'close_lb', :id => 'close_send_message_to_owner_lb', :title => 'close' %>
  <%= render :partial => 'messages/ajax_form', :locals => {:message_target => @tour_operator} %>

</div>

<%= render :partial => 'shared_partials/send_to_friends', :locals => {:item => 'tour_operator', :item_id => @tour_operator.id} %>
<%= render :partial => 'shared_partials/ownership_request', :locals => {:item => 'tour_operator', :item_id => @tour_operator.id} %>
<style type="text/css">

</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#detail_page_photo_gallery').galleryView(TBD.DETAIL_PAGE_PHOTO_GALLERY_OPTIONS);

    });


</script>